# Generated by Django 2.1.7 on 2019-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
