# Generated by Django 2.1.7 on 2019-04-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['netid', 'first_name', 'last_name', 'class_year']},
        ),
    ]
