# Generated by Django 2.1.7 on 2019-04-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190425_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'netid', 'class_year']},
        ),
    ]
