# Generated by Django 2.1.7 on 2019-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190326_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='netid',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
