# Generated by Django 2.1.7 on 2019-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190425_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='netid',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
