# Generated by Django 2.1.7 on 2019-03-21 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('code', models.CharField(max_length=3)),
                ('catalog_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
