# Generated by Django 2.1.7 on 2019-04-16 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['schedule', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['owner', '-term'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=5)),
                ('class_number', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('catalog_number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
