# Generated by Django 2.1.7 on 2019-03-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190327_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Section',
        ),
    ]
