# Generated by Django 2.1.7 on 2019-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190321_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='catalog_number',
            field=models.CharField(max_length=5),
        ),
    ]
