# Generated by Django 2.1.7 on 2019-04-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190416_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['code', 'catalog_number', 'section', 'title', 'start_time']},
        ),
    ]
