# Generated by Django 2.1.7 on 2019-03-30 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190330_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['owner']},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', related_query_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
