# Generated by Django 2.1.7 on 2019-03-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190330_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrentevent',
            options={'ordering': ['owner', 'schedule']},
        ),
    ]
