# Generated by Django 2.1.7 on 2019-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190331_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrentevent',
            options={'ordering': ['schedule', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='recurrentevent',
            name='owner',
        ),
    ]
