# Generated by Django 2.1.7 on 2019-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190331_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.CharField(default='F2018', max_length=5),
        ),
    ]
