# Generated by Django 2.1.7 on 2019-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_section_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.CharField(max_length=5),
        ),
    ]
