# Generated by Django 2.1.7 on 2019-04-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190402_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['owner', '-term']},
        ),
    ]
